# Generated by Django 5.1.1 on 2024-09-20 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_remove_client_last_login_alter_client_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=50, unique=True)),
                ('type_compte', models.CharField(choices=[('courant', 'Courant'), ('epargne', 'Epargne'), ('credit', 'Credit')], max_length=50)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_compte', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('bloque', 'Bloque')], default='actif', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.client')),
            ],
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_carte', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=50)),
                ('numero_carte', models.CharField(max_length=16, unique=True)),
                ('cvv', models.IntegerField()),
                ('date_emession', models.DateTimeField(auto_now_add=True)),
                ('limite_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('bloque', 'Bloqué'), ('expired', 'Expiré')], default='active', max_length=50)),
                ('solde_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code_pin', models.IntegerField()),
                ('date_expiration', models.DateField()),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.compte')),
            ],
        ),
    ]
