# Generated by Django 5.1.1 on 2024-09-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carte',
            old_name='date_emession',
            new_name='date_emission',
        ),
    ]
