# Generated by Django 5.1.1 on 2024-09-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_date_emession_carte_date_emission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='limite_credit',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='compte',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
