# Generated by Django 5.1.1 on 2024-09-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_carte_limite_credit_alter_compte_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='numero_compte',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
