# Generated by Django 5.1.1 on 2024-09-16 17:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('app_unite', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(unique=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('date_naissance', models.DateField(default=datetime.date(2004, 1, 1))),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('visiteur', 'Visiteur'), ('bloque', 'Bloque')], default='visiteur', max_length=10)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin'), ('X', 'Sac Walmart')], default='Masculin', max_length=100)),
                ('is_first', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.adresse')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
