# Generated by Django 5.1.1 on 2024-09-12 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(default=datetime.date(2004, 1, 1)),
        ),
    ]
