# Generated by Django 5.1.1 on 2024-09-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_client_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='genre',
            field=models.CharField(choices=[('Masculin', 'M'), ('Feminin', 'F'), ('Sac Walmart', 'X')], default='Masculin', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='is_first',
            field=models.BooleanField(default=True),
        ),
    ]
