# Generated by Django 5.1.1 on 2024-09-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_client_last_login_alter_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('bloque', 'Bloque')], default='visiteur', max_length=10),
        ),
    ]
