# Generated by Django 5.1.1 on 2024-09-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('visiteur', 'Visiteur'), ('bloque', 'Bloque')], default='visiteur', max_length=10),
        ),
    ]
