# Generated by Django 5.1.1 on 2024-09-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_client_genre_client_is_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin'), ('X', 'Sac Walmart')], default='Masculin', max_length=100),
        ),
    ]
